name = "dream-cloud"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "dream-inputs"
database_id = "28bf3fdb-3fd6-42f4-ad01-0bb3d30113d0" # We'll get this ID in the next step